name: Build
on:
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            # Check out current repository
            - name: Fetch Sources
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install CI
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Dependencies
              run: npm run install:all

            - name: Build Project
              run: npm run build
