on:
    push:
        tags:
            - "v*.*.*"

name: Build and Release VSIX

jobs:
    build:
        name: Build Project and VSIX
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Node Packages
              run: npm install
            - name: Package VSIX
              uses: lannonbr/vsce-action@3.0.0
              with:
                  args: "package"
            - name: Upload VSIX to Cache
              uses: actions/cache@v2
              with:
                  path: ./*.vsix
                  key: scorpio-${{ github.ref_name }}.vsix

    release:
        name: Release VSIX
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download VSIX from Cache
              uses: actions/cache@v2
              with:
                  path: ./*.vsix
                  key: scorpio-${{ github.ref_name }}.vsix
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
                  fail_on_unmatched_files: true
                  files: ./*.vsix
