# name: Sync Priority Field from Label

# on:
#   issues:
#     types: [labeled, unlabeled]

# jobs:
#   sync-priority-from-label:
#     runs-on: ubuntu-latest
#     environment: prod
#     if: startsWith(github.event.label.name, 'priority:')
#     steps:
#       - name: Check out the repository
#         uses: actions/checkout@v4

#       - name: Get Priority Severity from Label
#         id: priority_severity
#         run: |
#           PRIORITY=$(echo "${{ github.event.label.name }}" | cut -d':' -f2)
#           echo "PRIORITY=$PRIORITY" >> $GITHUB_OUTPUT
#           echo "PRIORITY=$PRIORITY" >> $GITHUB_STEP_SUMMARY

#       - name: Set Priority Field
#         if: github.event.action == 'labeled'
#         uses: alex-page/github-project-automation-plus@v0.9.0
#         with:
#           project: Priority
#           column: ${{ steps.priority_severity.outputs.PRIORITY }}
#           repo-token: ${{ secrets.PRIORITY_TOKEN }}

#       - name: Remove Priority Field
#         if: github.event.action == 'unlabeled'
#         uses: alex-page/github-project-automation-plus@v0.9.0
#         with:
#           project: Scorpio
#           column: ${{ steps.priority_severity.outputs.PRIORITY }}
#           action: remove
#           repo-token: ${{ secrets.PRIORITY_TOKEN }}

